---
- name: Check if mysql installed before
  shell: dpkg-query -l mysql
  register: mysql_installed
  failed_when: mysql_installed.rc > 1
  changed_when: no
 
- name: Add Percona repo key to system
  apt_key:  keyserver=keys.gnupg.net id=1C4CBDCDCD2EFD2A
  when: mysql_installed.stderr.find('no packages found') != 1  

- name: Add package definition
  apt_repository: repo="deb http://repo.percona.com/apt {{os_codename}} main"
  when: mysql_installed.stderr.find('no packages found') != 1  

- name: Install mysql-server
  apt: name={{mysql_package}} state=present update_cache=yes

- name: Make sure mysql is stopped just after installation
  service: name=mysql state=stopped
  when: mysql_installed.stderr.find('no packages found') != 1  

- name: Delete innodb log files created by apt package after initial install.
  shell: "rm -f {{ mysql_datadir }}/ib_logfile[01]"
  when: mysql_installed.stderr.find('no packages found') != 1  
