---
galaxy_info:
  author: Aydın Doyak
  description: Ansible role for Percona Mysql
  company: Tübitak ULAKBIM
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 1.8
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  - name: Debian
    versions:
    - jessie
    - wheezy
  categories:
  - database
  - database:sql
  - system
dependencies: []
