---

- name: make WP Content directory
  file: 
    path: /var/www/html/wordpress/wp-content/
    state: directory 
    owner: www-data 
    group: www-data 
    recurse: yes
  when: "{{ wc_new }} == 1"      
  tags:
    - software
    - wordpress
    - install 

- name: Download and Extract WordPress
  unarchive: 
    src: http://wordpress.org/latest.tar.gz
    dest: /var/www/html/
    copy: no
  when: "{{ wc_new }} == 1"      
  tags:
    - software
    - wordpress
    - install  
  
- name: Copy WordPress config file
  template: 
    src: wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php
  when: "{{ wc_new }} == 1"      
  tags:
    - software
    - wordpress
    - install  

- name: Copy DB config file
  template: 
    src: db-config.php.j2
    dest: /var/www/html/wordpress/db-config.php
  when: "{{ wc_new }} == 1"  
  tags:
    - software
    - wordpress
    - install  

- name: Copy DB file
  template: 
    src: db.php.j2
    dest: /var/www/html/wordpress/db.php
  when: "{{ wc_new }} == 1"    
  tags:
    - software
    - wordpress
    - install  

- name: Copy WordPress Nginx file
  template: 
    src: wordpress.j2
    dest: /etc/nginx/sites-available/wordpress
  when: "{{ wc_new }} == 1"
  tags:
    - software
    - wordpress
    - install  

- name: Symlink WordPress nginx available as enabled
  file: 
    src: /etc/nginx/sites-available/wordpress
    dest: /etc/nginx/sites-enabled/wordpress 
    state: link
  when: "{{ wc_new }} == 1"    
  tags:
    - software
    - wordpress
    - install 

- name: Remove default nginx as enabled
  file: 
    path: /etc/nginx/sites-enabled/default
    state: absent
  when: "{{ wc_new }} == 1"    
  tags:
    - software
    - wordpress
    - install 

- name: Change ownership of WordPress installation
  file: 
    path: /var/www/html/wordpress/
    owner: www-data 
    group: www-data 
    state: directory 
    recurse: yes
    mode: 0755 
  tags:
    - software
    - wordpress
    - install      

- name: restart nginx
  service: name=nginx state=restarted
  tags:
    - software
    - wordpress
    - install 


- name: make WP Cli directory
  file: 
    path: /usr/local/bin/wp/
    state: directory 
    owner: www-data 
    group: www-data 
    recurse: yes
  tags:
    - software
    - wordpress
    - install 


- name: Get wp-cli file
  get_url: 
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp/wp-cli.phar
    owner: www-data 
    group: www-data    
    mode: u+rwx 
  tags:
    - software
    - wordpress
    - install 

- name: Get wp-cli file
  get_url: 
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp
    owner: www-data 
    group: www-data    
    mode: u+rwx 
  tags:
    - software
    - wordpress
    - install 

- name: Symlink WordPress folder
  file: 
    src: /var/www/html/wordpress
    dest: /wp
    state: link
  when: "{{ wc_new }} == 1"    
  tags:
    - software
    - wordpress
    - install 
