---
language: python
python: 2.7

env:
  - SITE=test.yml

before_install: 

  - sudo apt-get update -qq
  - sudo apt-get remove --purge mysql*
  - sudo apt-get autoremove && sudo apt-get autoclean
  - sudo rm -rf /var/lib/mysql && sudo rm -rf /var/log/mysql

install:

  - pip install ansible
  -  "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:

  - "ansible-playbook -i tests/inventory tests/$SITE --syntax-check"
  - "ansible-playbook -i tests/inventory tests/$SITE --connection=local --sudo"

  - "sudo ls -lah /var/log"
  - "sudo cat /var/log/mysql/mysql.err"

  - >
    mysql -u root -proot -e 'show databases;'
    | grep -q 'performance_schema'
    && (echo 'MySQL running normally' && exit 0)
    || (echo 'MySQL not running' && exit 1)

  - >
    mysql -u root -proot -h 127.0.0.1 -e 'show databases;'
    | grep -q 'performance_schema'
    && (echo 'MySQL running normally' && exit 0)
    || (echo 'MySQL not running' && exit 1)
